version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: cintos_fashion_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cintos_fashion
      MYSQL_USER: cintos_user
      MYSQL_PASSWORD: cintos_password
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: